export const INCREMENT_BY_ONE = "INCREMENT_BY_ONE";
export const DECREMENT_BY_ONE = "DECREMENT_BY_ONE";
export const INCREMENT_BY_VALUE = "INCREMENT_BY_VALUE";
export const DECREMENT_BY_VALUE = "DECREMENT_BY_VALUE";
export const RESET_COUNTER = "RESET_COUNTER";
